### ISSUE TITLE
Latest atom update has stoped this package from working

### ISSUE THREAD

**Issue by CyborgSemon** [UziTech/atom-open#5] opened 2019-04-26 03:48 UTC
Atom just updated, and now I cant seem to get any of this packages features to work.
Current atom version: 1.36.1
Current MacOS version: 10.14.4

**Comment by UziTech** [comment] 2019-04-26 13:17
Can you provide a link that isn't working?

**Comment by UziTech** [comment] 2019-04-26 13:28
looks like the issue is https://github.com/atom/atom/commit/952c42c0de8cdab2661856f5dd4789a1d69e08ee changed the name of a setting

**Comment by UziTech** [comment] 2019-04-26 13:34
This is fixed in v2.0.2

**Closed by UziTech** 2019-04-26 13:34 UTC
Labels: needs more info

**Comment by CyborgSemon** [comment] 2019-04-26 22:45
Works great now thanks!
